version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: superset
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  superset:
    build: .
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_CONFIG_PATH=/app/superset_config_datafusion.py
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://superset:superset_password@mysql:3306/superset
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./users.parquet:/app/users.parquet
      - ./setup.sql:/app/setup.sql
      - ./init_superset.sh:/app/init_superset.sh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  mysql_data:
